# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      require_serial: true
      args:
        [
          "--logging-format-style=new",
          "--fail-under=8",
          "--fail-on=E,W", # fail if errors, critical, or warnings (refactor / convention OK)
          "--disable=too-many-locals,too-many-positional-arguments,no-name-in-module,protected-access,too-many-arguments", # disable errors like ' No name 'MolToSmiles' in module 'rdkit.Chem' (no-name-in-module)' since rdkit special
          "-rn", # Only display messages
        ]
    - id: pytest
      name: pytest
      entry: python hill_test.py
      language: system
      types: [ python ]
      pass_filenames: false
      always_run: false
